# Generated by Django 5.2.10 on 2026-01-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=50)),
                ('mobileNumber', models.CharField(default='', max_length=50)),
                ('expertise', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_doctor',
            },
        ),
    ]
