# Generated by Django 5.2.10 on 2026-01-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0002_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='expertise',
            new_name='roleName',
        ),
    ]
